variables:
  ERL_LIBS: "./libs"

stages:
  - lint
  - dialyzer
  - eunit
  - eqc
  - package

lint:
  stage: lint
  script:
    - ./rebar3 as lint lint
  tags:
    - erlagn-19

dialyzer:
  stage: dialyzer
  script:
    - ./rebar3 dialyzer
  tags:
    - erlagn-19

eunit:
  stage: eunit
  script:
    - ./rebar3 eunit
  tags:
    - erlagn-19

package-bsd:
  stage: package
  script:
    - gmake dist
  tags:
    - bsd

package-smartos:
  stage: package
  script:
    - gmake dist
  tags:
    - smartos

.eqc_template: &eqc_definition
  stage: eqc
  script:
    - mkdir libs
    - cd libs
    - curl -Ol http://www.quviq.com/wp-content/uploads/2015/09/eqcmini-2.01.0.zip
    - unzip eqcmini-2.01.0.zip
    - cd ..
    - epmd &
    - ./rebar3 as eqc eqc

eqc-smartos:
  <<: *eqc_definition
  tags:
    - smartos

eqc-bsd:
  <<: *eqc_definition
  tags:
    - bsd

eqc-linux:
  <<: *eqc_definition
  image: erlang:20
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends unzip
  tags:
    - linux
